### ISSUE TITLE
Yarn build is failing to run

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#244]
I am running 
Tractor version 1.7.0
Node version v10.15.3
NPM version 6.4.1

When I run yarn build it is getting to this point and failing 

```
@tractor-plugins/screen-size: { Error: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "npm run test:e2e"
@tractor-plugins/screen-size:     at makeError (C:\Users\tbiddle\Documents\GitHub\tractor\node_modules\start-server-and-test\node_modules\execa\index.js:174:9)
@tractor-plugins/screen-size:     at Promise.all.then.arr (C:\Users\tbiddle\Documents\GitHub\tractor\node_modules\start-server-and-test\node_modules\execa\index.js:278:16)
@tractor-plugins/screen-size:     at process._tickCallback (internal/process/next_tick.js:68:7)
@tractor-plugins/screen-size:   code: 100,
@tractor-plugins/screen-size:   stdout: null,
@tractor-plugins/screen-size:   stderr: null,
@tractor-plugins/screen-size:   failed: true,
@tractor-plugins/screen-size:   signal: null,
@tractor-plugins/screen-size:   cmd: 'C:\\WINDOWS\\system32\\cmd.exe /q /s /c "npm run test:e2e"',
@tractor-plugins/screen-size:   timedOut: false,
@tractor-plugins/screen-size:   killed: false }
@tractor-plugins/screen-size: error Command failed with exit code 1.
@tractor-plugins/screen-size: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test:e2e:ci exited 1 in '@tractor-plugins/screen-size'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
C:\Users\tbiddle\Documents\GitHub\tractor>
DevTools listening on ws://127.0.0.1:58627/devtools/browser/b68ecf91-fc77-4a9d-ad40-e62d1fb704b8

DevTools listening on ws://127.0.0.1:58667/devtools/browser/d309acf0-d18c-4907-ac87-a9a441d01c64
```

**Comment by TRBPRO23** [comment]
This issue was being caused by an old version of Firefox. Updating it fixes the issue.
