### ISSUE TITLE
Unhandled rejection TypeError: when moving files

### ISSUE THREAD

**Issue by TRBPRO23** [TradeMe/tractor#51]
When moving files around, tractor throws an error (intermittent)

Unhandled rejection TypeError: Cannot read property 'directories' of undefined
at C:/Users/tbiddle/AppData/Roaming/npm/node_modules/tractor/server/api/edit-item-path.js:129:29
at tryCatcher (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\util.js:26:23)
at Promise._settlePromiseFromHandler (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\prom
ise.js:507:31)
at Promise._settlePromiseAt (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\promise.js:58
1:18)
at Promise._settlePromises (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\promise.js:697
:14)
at Async._drainQueue (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\async.js:123:16)
at Async._drainQueues (C:\Users\tbiddle\AppData\Roaming\npm\node_modules\tractor\node_modules\bluebird\js\main\async.js:133:10)
at Immediate.Async.drainQueues [as _onImmediate](C:UserstbiddleAppDataRoamingnpmnode_modulestractornode_modulesbluebird
jsmainasync.js:15:14)
at processImmediate [as _immediateCallback](timers.js:374:17)

**Comment by TRBPRO23** [comment]
Issue fixed in latest version of Tractor
